
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class ToolbarMenu extends javax.swing.JFrame {

    /**
     * Creates new form ToolbarMenu
     */
    public ToolbarMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mGantiWarna = new javax.swing.JMenu();
        miMerah = new javax.swing.JMenuItem();
        miHijau = new javax.swing.JMenuItem();
        miBiru = new javax.swing.JMenuItem();
        toolbar = new javax.swing.JToolBar();
        New = new javax.swing.JButton();
        Preview = new javax.swing.JButton();
        Setting = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        mGantiWarna.setText("Ganti Warna Background");

        miMerah.setText("Merah");
        miMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMerahActionPerformed(evt);
            }
        });
        mGantiWarna.add(miMerah);

        miHijau.setText("Hijau");
        miHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHijauActionPerformed(evt);
            }
        });
        mGantiWarna.add(miHijau);

        miBiru.setText("Biru");
        miBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBiruActionPerformed(evt);
            }
        });
        mGantiWarna.add(miBiru);

        jPopupMenu1.add(mGantiWarna);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbar.setRollover(true);
        toolbar.setName(""); // NOI18N

        New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Text.png"))); // NOI18N
        New.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        New.setFocusable(false);
        New.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        New.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });
        toolbar.add(New);

        Preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Text preview.png"))); // NOI18N
        Preview.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Preview.setFocusable(false);
        Preview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Preview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviewActionPerformed(evt);
            }
        });
        toolbar.add(Preview);

        Setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Application.png"))); // NOI18N
        Setting.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Setting.setFocusable(false);
        Setting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Setting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingActionPerformed(evt);
            }
        });
        toolbar.add(Setting);

        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        Add.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        Add.setFocusable(false);
        Add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Add.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        toolbar.add(Add);

        Panel.setComponentPopupMenu(jPopupMenu1);

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ini adalah aplikasi GUI berbasis Java");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void miMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMerahActionPerformed
        // TODO add your handling code here:
        Panel.setBackground(Color.red);
    }//GEN-LAST:event_miMerahActionPerformed

    private void miHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHijauActionPerformed
        // TODO add your handling code here:
        Panel.setBackground(Color.green);
    }//GEN-LAST:event_miHijauActionPerformed

    private void miBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBiruActionPerformed
        // TODO add your handling code here:
        Panel.setBackground(Color.blue);
    }//GEN-LAST:event_miBiruActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here: 
        JOptionPane.showMessageDialog(null, "Silahkan Tambahkan new project");
    }//GEN-LAST:event_NewActionPerformed

    private void PreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviewActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Silahkan cari apa yang anda inginkan");
    }//GEN-LAST:event_PreviewActionPerformed

    private void SettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Silahkan Setting yang anda butuhkan");
    }//GEN-LAST:event_SettingActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Silahkan tambahkan apa yang anda inginkan");
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToolbarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToolbarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToolbarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToolbarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToolbarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton New;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton Preview;
    private javax.swing.JButton Setting;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu mGantiWarna;
    private javax.swing.JMenuItem miBiru;
    private javax.swing.JMenuItem miHijau;
    private javax.swing.JMenuItem miMerah;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables

    
}
